# Generated by Django 5.2.8 on 2025-12-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('CAMPUS_TO_CITY', 'Campus to City'), ('CAMPUS_TO_BRTCDEPOT', 'Campus to BRTC Depot'), ('CAMPUS_TO_DOSHMILE', 'Campus to Doshmile'), ('CITY_TO_CAMPUS', 'City to Campus')], max_length=20)),
                ('day_type', models.CharField(choices=[('SUN_THU', 'Sunday to Thursday (Regular)'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('TUE', 'Tuesday (Special)')], default='SUN_THU', max_length=10)),
                ('departure_time', models.TimeField()),
                ('bus_number', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(default='secret_key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_stop_order', models.IntegerField(default=0)),
                ('last_direction', models.CharField(default='STOPPED', max_length=50)),
                ('trip_status', models.CharField(choices=[('IDLE', 'Idle'), ('READY', 'Ready'), ('ON_TRIP', 'On Trip')], default='IDLE', max_length=20)),
                ('last_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
            ],
            options={
                'indexes': [models.Index(fields=['bus', '-timestamp'], name='core_busloc_bus_id_b749d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequence number (e.g. 1, 2, 3)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
