# Generated by Django 5.2.8 on 2025-12-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_contact',
            field=models.DateTimeField(auto_now=True, help_text='Last time device sent data'),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.bus'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='direction',
            field=models.CharField(choices=[('CAMPUS_TO_CITY', 'Campus to City'), ('CAMPUS_TO_BRTCDEPOT', 'Campus to BRTC Depot'), ('CAMPUS_TO_DOSHMILE', 'Campus to Doshmile'), ('CITY_TO_CAMPUS', 'City to Campus'), ('BRTCDEPOT_TO_CAMPUS', 'BRTC Depot to Campus'), ('DOSHMILE_TO_CAMPUS', 'Doshmile to Campus'), ('TERMINAL_TO_CAMPUS', 'Terminal to campus'), ('SUIHARI_TO_CAMPUS', 'Suihari to campus'), ('BALIBARI_TO_CAMPUS', 'Balibari to campus')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['timestamp'], name='core_busloc_timesta_1e6b7e_idx'),
        ),
    ]
