# Generated by Django 5.2.8 on 2025-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_direction',
            field=models.CharField(default='STOPPED', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_stop_order',
            field=models.IntegerField(default=0),
        ),
    ]
