# Generated by Django 5.2.8 on 2025-12-31 06:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_current_latitude_bus_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='api_key',
            field=models.CharField(default=core.models.generate_api_key, help_text='এটি হার্ডওয়্যার ডিভাইসের জন্য গোপন কি (Secret Key)', max_length=100, unique=True),
        ),
    ]
