# Generated by Django 5.2.8 on 2025-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_last_direction_bus_last_stop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='trip_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('READY', 'Ready'), ('ON_TRIP', 'On Trip')], default='IDLE', max_length=20),
        ),
    ]
