# Generated by Django 5.2.8 on 2025-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bus_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['bus', '-timestamp'], name='core_busloc_bus_id_b749d1_idx'),
        ),
    ]
