# Generated by Django 5.2.8 on 2025-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bus_last_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('CAMPUS_TO_CITY', 'Campus to City'), ('CITY_TO_CAMPUS', 'City to Campus')], max_length=20)),
                ('day_type', models.CharField(choices=[('SUN_THU', 'Sunday to Thursday (Regular)'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('TUE', 'Tuesday (Special)')], default='SUN_THU', max_length=10)),
                ('departure_time', models.TimeField()),
                ('bus_number', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
    ]
