# Generated by Django 5.2.8 on 2025-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_busschedule_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='direction',
            field=models.CharField(choices=[('CAMPUS_TO_CITY', 'Campus to City'), ('CAMPUS_TO_BRTCDEPOT', 'Campus to BRTC Depot'), ('CAMPUS_TO_DOSHMILE', 'Campus to Doshmile'), ('CITY_TO_CAMPUS', 'City to Campus')], max_length=20),
        ),
    ]
