# Generated by Django 5.2.8 on 2025-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Paste image link here', max_length=500, null=True),
        ),
    ]
