# Generated by Django 5.2.8 on 2025-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='ছবির লিংক দিন', max_length=500, null=True)),
                ('contact_number', models.CharField(default='017xxxxxxxx', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
